version: "3.2"

services:
  applepaymerchant:
    image: clearhaus/applepaymerchant
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/applepaymerchant
