version: 2

jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      DOCKER_IMAGE: clearhaus/applepaymerchant
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            echo "LABEL compare=$CIRCLE_COMPARE_URL" >> build/Dockerfile
            sh build/build.sh
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$CIRCLE_SHA1
      - deploy:
          name: Push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "Pushing to :latest tag"
              docker push $DOCKER_IMAGE
            else
              echo "Pushing to tag $CIRCLE_SHA1"
              docker push $DOCKER_IMAGE:$CIRCLE_SHA1
            fi
